import sqlite3

# Connect to the database (creates it if it doesn't exist)
conn = sqlite3.connect('health_data.db')
cursor = conn.cursor()

# Drop the existing table if it exists
cursor.execute('DROP TABLE IF EXISTS patients')

# Create the table
cursor.execute('''
CREATE TABLE IF NOT EXISTS patients
(id INTEGER PRIMARY KEY, 
 age INTEGER, 
 gender TEXT, 
 symptom1 TEXT, 
 symptom2 TEXT, 
 symptom3 TEXT, 
 diagnosis TEXT)
''')
# Insert some sample data
sample_data = [
    (1, 35, 'M', 'fever', 'cough', 'fatigue', 'flu'),
    (2, 50, 'F', 'chest pain', 'shortness of breath', 'dizziness', 'heart disease'),
    (3, 29, 'M', 'nausea', 'headache', 'fatigue', 'migraine'),
    (4, 67, 'F', 'cough', 'shortness of breath', 'fatigue', 'bronchitis'),
    (5, 45, 'M', 'dizziness', 'nausea', 'headache', 'hypertension'),
    (6, 21, 'F', 'sore throat', 'cough', 'fatigue', 'infection'),
    (7, 32, 'M', 'fever', 'headache', 'chills', 'malaria'),
    (8, 54, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (9, 43, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (10, 36, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (11, 28, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (12, 39, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (13, 61, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (14, 47, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (15, 53, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (16, 22, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (17, 44, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (18, 35, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (19, 58, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (20, 49, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (21, 42, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (22, 30, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (23, 55, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (24, 37, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (25, 46, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (26, 51, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (27, 63, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (28, 41, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (29, 33, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (30, 29, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (31, 34, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (32, 47, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (33, 52, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (34, 39, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (35, 48, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (36, 27, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (37, 59, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (38, 45, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (39, 38, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (40, 56, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (41, 32, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (42, 50, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (43, 44, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (44, 29, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (45, 41, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (46, 36, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (47, 53, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (48, 34, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (49, 48, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (50, 27, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (51, 54, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (52, 37, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (53, 39, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (54, 59, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (55, 30, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (56, 49, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (57, 35, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (58, 31, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (59, 43, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (60, 46, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (61, 51, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (62, 40, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (63, 52, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (64, 36, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (65, 33, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (66, 42, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (67, 38, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (68, 57, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (69, 28, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (70, 47, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (71, 34, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (72, 30, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (73, 44, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (74, 35, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (75, 55, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (76, 31, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (77, 50, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (78, 39, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (79, 32, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (80, 41, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (81, 45, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (82, 53, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (83, 29, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (84, 49, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (85, 38, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (86, 34, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (87, 42, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (88, 37, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (89, 58, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (90, 33, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (91, 52, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (92, 40, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (93, 37, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (94, 44, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (95, 41, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (96, 56, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (97, 28, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (98, 48, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (99, 39, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (100, 35, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (101, 43, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (102, 36, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (103, 54, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (104, 31, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (105, 51, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (106, 42, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (107, 34, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (108, 46, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (109, 38, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (110, 55, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (111, 30, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (112, 47, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (113, 36, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (114, 32, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (115, 41, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (116, 35, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (117, 52, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (118, 37, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (119, 50, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (120, 29, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (121, 34, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (122, 42, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (123, 33, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (124, 58, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (125, 35, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (126, 49, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (127, 38, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (128, 40, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (129, 44, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (130, 39, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (131, 57, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (132, 29, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (133, 48, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (134, 37, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (135, 30, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (136, 46, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (137, 34, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (138, 56, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (139, 33, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (140, 50, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (141, 41, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (142, 35, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (143, 44, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (144, 38, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (145, 53, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (146, 32, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (147, 49, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (148, 29, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (149, 37, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (150, 43, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (151, 36, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (152, 51, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (153, 34, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (154, 48, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (155, 40, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (156, 30, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (157, 45, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (158, 37, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (159, 54, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (160, 32, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (161, 47, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (162, 28, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (163, 36, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (164, 40, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (165, 35, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (166, 55, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (167, 33, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (168, 48, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (169, 39, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (170, 31, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (171, 43, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (172, 38, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (173, 57, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (174, 29, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (175, 49, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (176, 34, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (177, 32, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (178, 45, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (179, 39, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (180, 53, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (181, 31, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (182, 47, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (183, 36, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (184, 33, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (185, 42, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (186, 37, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
    (187, 51, 'M', 'fever', 'chills', 'sweating', 'flu'),
    (188, 28, 'F', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (189, 46, 'M', 'rash', 'itching', 'swelling', 'allergy'),
    (190, 38, 'F', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (191, 29, 'M', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (192, 44, 'F', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (193, 35, 'M', 'runny nose', 'sneezing', 'cough', 'cold'),
    (194, 52, 'F', 'fever', 'chills', 'sweating', 'flu'),
    (195, 32, 'M', 'ear pain', 'discharge', 'headache', 'ear infection'),
    (196, 49, 'F', 'rash', 'itching', 'swelling', 'allergy'),
    (197, 41, 'M', 'joint pain', 'swelling', 'fatigue', 'arthritis'),
    (198, 30, 'F', 'abdominal pain', 'bloating', 'diarrhea', 'gastroenteritis'),
    (199, 43, 'M', 'vomiting', 'nausea', 'headache', 'food poisoning'),
    (200, 36, 'F', 'runny nose', 'sneezing', 'cough', 'cold'),
]
cursor.executemany('INSERT INTO patients VALUES (?,?,?,?,?,?,?)', sample_data)

# Commit the changes
conn.commit()

# Verify data insertion
cursor.execute('SELECT COUNT(*) FROM patients')
count = cursor.fetchone()[0]
print(f"Number of records inserted: {count}")

# Close the connection
conn.close()

print("Database created and sample data inserted successfully!")